### **Exemplo - Exercício 8**

In [9]:
import pandas as pd
import numpy as np
import os

#### **Leitura do arquivo csv**

In [10]:
data_path = os.path.join(os.getcwd(),'data_exemplo.csv')
df = pd.read_csv(data_path)

#### **Exibindo as primeiras linhas**

In [11]:
display(df.head()) # Exibindo as cinco primeiras linhas (default)

,id,marca,ram_gb,armazenamento_gb,nucleos_cpu,vram_gpu_gb,clock_cpu_ghz,preco_rs
0,1,Apple,8,256,8,4,2.71,4860.08
1,2,Acer,8,2048,4,0,2.30,5267.20
2,3,Dell,8,512,16,8,2.71,7078.96
3,4,HP,16,2048,8,6,2.50,8161.93
4,5,HP,8,256,12,0,3.15,4468.57

In [12]:
display(df.head(3)) # Exibindo as três primeiras linhas

,id,marca,ram_gb,armazenamento_gb,nucleos_cpu,vram_gpu_gb,clock_cpu_ghz,preco_rs
0,1,Apple,8,256,8,4,2.71,4860.08
1,2,Acer,8,2048,4,0,2.30,5267.20
2,3,Dell,8,512,16,8,2.71,7078.96

In [13]:
display(df.head(10)) # Exibindo as dez primeiras linhas

,id,marca,ram_gb,armazenamento_gb,nucleos_cpu,vram_gpu_gb,clock_cpu_ghz,preco_rs
0,1,Apple,8,256,8,4,2.71,4860.08
1,2,Acer,8,2048,4,0,2.30,5267.20
2,3,Dell,8,512,16,8,2.71,7078.96
3,4,HP,16,2048,8,6,2.50,8161.93
4,5,HP,8,256,12,0,3.15,4468.57
5,6,Acer,8,2048,16,0,5.11,7435.72
6,7,Lenovo,32,1024,16,4,4.25,8641.29
7,8,HP,32,256,6,0,3.22,5561.25
8,9,Apple,16,1024,8,4,4.14,6543.89
9,10,HP,8,512,16,16,2.78,8609.76

#### **Exibindo as ùltimas linhas**

In [14]:
display(df.tail()) # Exibindo as cinco últimas linhas (default)

,id,marca,ram_gb,armazenamento_gb,nucleos_cpu,vram_gpu_gb,clock_cpu_ghz,preco_rs
25,26,Dell,16,512,4,0,4.27,4156.72
26,27,Lenovo,8,1024,4,12,2.76,6746.19
27,28,Dell,16,2048,6,8,4.58,8009.85
28,29,Apple,64,1024,12,8,3.49,11735.25
29,30,Lenovo,8,256,12,16,3.09,7973.20

In [15]:
display(df.tail(10)) # Exibindo as dez últimas linhas

,id,marca,ram_gb,armazenamento_gb,nucleos_cpu,vram_gpu_gb,clock_cpu_ghz,preco_rs
20,21,Dell,32,512,4,4,4.81,6823.57
21,22,Acer,64,256,16,4,2.41,10353.37
22,23,Acer,16,1024,16,12,3.35,8970.88
23,24,Acer,16,1024,12,16,4.08,9379.66
24,25,Acer,64,256,6,4,2.20,8559.82
25,26,Dell,16,512,4,0,4.27,4156.72
26,27,Lenovo,8,1024,4,12,2.76,6746.19
27,28,Dell,16,2048,6,8,4.58,8009.85
28,29,Apple,64,1024,12,8,3.49,11735.25
29,30,Lenovo,8,256,12,16,3.09,7973.20

In [16]:
display(df.tail(2)) # Exibindo as 2 últimas linhas

,id,marca,ram_gb,armazenamento_gb,nucleos_cpu,vram_gpu_gb,clock_cpu_ghz,preco_rs
28,29,Apple,64,1024,12,8,3.49,11735.25
29,30,Lenovo,8,256,12,16,3.09,7973.20