### **Exemplo - Exercício 8**

In [10]:
import pandas as pd
import numpy as np
import os

#### **Leitura do arquivo csv**

In [11]:
data_path = os.path.join(os.getcwd(),'data_exemplo.csv')
df = pd.read_csv(data_path)

#### **Exibindo as primeiras linhas**

In [12]:
display(df.head()) # Exibindo os cinco primeiros (default)

,id,marca,ram_gb,armazenamento_gb,nucleos_cpu,vram_gpu_gb,clock_cpu_ghz,preco_rs
0,1,Apple,8,256,8,4,2.71,4860.08
1,2,Acer,8,2048,4,0,2.30,5267.20
2,3,Dell,8,512,16,8,2.71,7078.96
3,4,HP,16,2048,8,6,2.50,8161.93
4,5,HP,8,256,12,0,3.15,4468.57

In [13]:
display(df.head(3)) # Exibindo os três primeiros

,id,marca,ram_gb,armazenamento_gb,nucleos_cpu,vram_gpu_gb,clock_cpu_ghz,preco_rs
0,1,Apple,8,256,8,4,2.71,4860.08
1,2,Acer,8,2048,4,0,2.30,5267.20
2,3,Dell,8,512,16,8,2.71,7078.96

In [14]:
display(df.head(10)) # Exibindo os dez primeiros

,id,marca,ram_gb,armazenamento_gb,nucleos_cpu,vram_gpu_gb,clock_cpu_ghz,preco_rs
0,1,Apple,8,256,8,4,2.71,4860.08
1,2,Acer,8,2048,4,0,2.30,5267.20
2,3,Dell,8,512,16,8,2.71,7078.96
3,4,HP,16,2048,8,6,2.50,8161.93
4,5,HP,8,256,12,0,3.15,4468.57
5,6,Acer,8,2048,16,0,5.11,7435.72
6,7,Lenovo,32,1024,16,4,4.25,8641.29
7,8,HP,32,256,6,0,3.22,5561.25
8,9,Apple,16,1024,8,4,4.14,6543.89
9,10,HP,8,512,16,16,2.78,8609.76